# Generated by Django 4.2.7 on 2023-11-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_deposit_expense_details_expense_head_monthlysummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ex_detail', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.CharField(default='Nil', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Socity_member',
            new_name='SocityMember',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='category',
            new_name='fund_head',
        ),
        migrations.AddField(
            model_name='deposit',
            name='remark',
            field=models.CharField(default='Nil', max_length=200),
        ),
        migrations.RenameModel(
            old_name='Expense_head',
            new_name='ExpenseHead',
        ),
        migrations.DeleteModel(
            name='Expense_details',
        ),
        migrations.AddField(
            model_name='expensedetails',
            name='ex_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.expensehead'),
        ),
    ]
