# Generated by Django 4.2.7 on 2023-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_expensedetails_rename_socity_member_socitymember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socitymember',
            name='society_designation',
            field=models.CharField(default='General Member', max_length=255),
        ),
    ]
